import { createSlice } from '@reduxjs/toolkit';
const initialState = {
  /** 数据字典 */
  dictData: {},
  /** 菜单列表 */
  menusList: [],
  /** 用户信息 */
  user: {
    id: '',
    username: '',
    role: [],
  },
};

export const userInfoSlice = createSlice({
  name: 'userInfo',
  initialState,
  reducers: {
    setUserInfo: (state, action) => {
      // 遍历 payload，动态更新字段
      Object.entries(action.payload)?.forEach(([key, value]) => {
        state[key] = value;
      });
    },
  },
});

export const { setUserInfo } = userInfoSlice.actions;

export default userInfoSlice.reducer;

// export const menuIni = [
//   {
//     id: '1',
//     pid: 0,
//     name: '首页',
//     path: '/',
//     icon: 'HomeOutlined',
//     cmpPath: 'pages/home',
//     isShow: '1',
//     isRouter: '0',
//     sort: 1,
//   },
//   {
//     id: '997',
//     pid: 0,
//     name: 'chat',
//     path: '/chat',
//     icon: 'HomeOutlined',
//     cmpPath: 'pages/chat',
//     isShow: '1',
//     isRouter: '1',
//     sort: 1,
//   },
//   {
//     id: '998',
//     pid: 0,
//     name: 'demo',
//     path: '/demo',
//     icon: 'HomeOutlined',
//     cmpPath: 'pages/demo',
//     isShow: '1',
//     isRouter: '1',
//     sort: 1,
//   },
//   {
//     id: '2',
//     pid: 0,
//     name: '统计分析',
//     path: '/statistics',
//     icon: 'IdcardOutlined',
//     isShow: '1',
//     isRouter: '1',
//     sort: 2,
//   },
//   {
//     id: '2-1',
//     pid: '2',
//     name: '集群统计',
//     path: '/statistics/colony',
//     cmpPath: 'pages/statistics/colony',
//     isShow: '1',
//     isRouter: '1',
//     sort: 1,
//   },
//   {
//     id: '2-2',
//     pid: '2',
//     name: '系统统计',
//     path: '/statistics/system',
//     cmpPath: 'pages/statistics/system',
//     isShow: '1',
//     isRouter: '1',
//     sort: 2,
//   },
//   {
//     id: '2-3',
//     pid: '2',
//     name: 'API统计',
//     path: '/statistics/api',
//     cmpPath: 'pages/statistics/api',
//     isShow: '1',
//     isRouter: '1',
//     sort: 3,
//   },
//   {
//     id: '2-4',
//     pid: '2',
//     name: '日志统计',
//     path: '/statistics/log',
//     cmpPath: 'pages/statistics/log',
//     isShow: '1',
//     isRouter: '1',
//     sort: 4,
//   },
//   {
//     id: '5',
//     pid: 0,
//     name: 'API管理',
//     path: '/gatewayApi',
//     icon: 'IdcardOutlined',
//     // cmpPath: "pages/demo",
//     isShow: '1',
//     isRouter: '1',
//     sort: 1,
//   },
//   {
//     id: '5-1',
//     pid: '5',
//     name: 'API管理',
//     path: '/gatewayApi/api',
//     cmpPath: 'pages/gatewayApi/api',
//     isShow: '1',
//     isRouter: '1',
//     sort: 1,
//   },
//   {
//     id: '5-2',
//     pid: '5',
//     name: '系统管理',
//     path: '/gatewayApi/system',
//     cmpPath: 'pages/gatewayApi/system',
//     isShow: '1',
//     isRouter: '1',
//     sort: 2,
//   },
//   {
//     id: '5-3',
//     pid: '5',
//     name: '上游管理',
//     path: '/gatewayApi/upstream',
//     cmpPath: 'pages/gatewayApi/upstream',
//     isShow: '1',
//     isRouter: '1',
//     sort: 3,
//   },
//   {
//     id: '5-4',
//     pid: '5',
//     name: '消费者管理',
//     path: '/gatewayApi/consumer',
//     cmpPath: 'pages/gatewayApi/consumer',
//     isShow: '1',
//     isRouter: '1',
//     sort: 4,
//   },
//   {
//     id: '5-5',
//     pid: '5',
//     name: '插件管理',
//     path: '/gatewayApi/plugins',
//     cmpPath: 'pages/gatewayApi/plugins',
//     isShow: '1',
//     isRouter: '1',
//     sort: 5,
//   },
//   {
//     id: '6',
//     pid: 0,
//     name: '权限管理',
//     path: '/system',
//     icon: 'IdcardOutlined',
//     isShow: '1',
//     isRouter: '1',
//     sort: 1,
//   },
//   {
//     id: '6-1',
//     pid: '6',
//     name: '用户管理',
//     path: '/system/user',
//     cmpPath: 'pages/system/user',
//     isShow: '1',
//     isRouter: '1',
//     sort: 1,
//   },
//   {
//     id: '6-2',
//     pid: '6',
//     name: '角色管理',
//     path: '/system/role',
//     cmpPath: 'pages/system/role',
//     isShow: '1',
//     isRouter: '1',
//     sort: 2,
//   },
//   {
//     id: '6-3',
//     pid: '6',
//     name: '菜单管理',
//     path: '/system/menu',
//     cmpPath: 'pages/system/menu',
//     isShow: '1',
//     isRouter: '1',
//     sort: 3,
//   },
//   {
//     id: '6-4',
//     pid: '6',
//     name: '集群管理',
//     path: '/system/colony',
//     cmpPath: 'pages/system/colony',
//     isShow: '1',
//     isRouter: '1',
//     sort: 4,
//   },
//   {
//     id: '7',
//     pid: 0,
//     name: '监控服务',
//     path: '/monitor',
//     icon: 'IdcardOutlined',
//     isShow: '1',
//     isRouter: '1',
//     sort: 1,
//   },
//   {
//     id: '7-1',
//     pid: '7',
//     name: '系统监控',
//     path: '/monitor/system',
//     cmpPath: 'pages/monitor/system',
//     isShow: '1',
//     isRouter: '1',
//     sort: 1,
//   },
//   {
//     id: '7-2',
//     pid: '7',
//     name: '应用监控',
//     path: '/monitor/app',
//     cmpPath: 'pages/monitor/app',
//     isShow: '1',
//     isRouter: '1',
//     sort: 2,
//   },
//   {
//     id: '3',
//     pid: 0,
//     name: '菜单测试',
//     path: '/menuDemo',
//     icon: 'IdcardOutlined',
//     // cmpPath: "pages/demo",
//     isShow: '1',
//     isRouter: '1',
//     sort: 0,
//   },
//   {
//     id: '3-1',
//     pid: '3',
//     name: '菜单测试1',
//     path: '/menuDemo/menuDemoOne',
//     // cmpPath: "pages/menuDemo/",
//     isShow: '1',
//     isRouter: '1',
//     sort: 0,
//   },
//   {
//     id: '3-1-1',
//     pid: '3-1',
//     name: '菜单测试3-1-1',
//     path: '/menuDemo/menuDemoOne/menuDemoOneOne',
//     cmpPath: 'pages/menuDemo/menuDemoOne/menuDemoOneOne',
//     isShow: '1',
//     isRouter: '1',
//     sort: 0,
//   },
//   {
//     id: '3-1-2',
//     pid: '3-1',
//     name: '菜单测试3-1-2',
//     path: '/menuDemo/menuDemoOne/menuDemoOneTwo',
//     cmpPath: 'pages/menuDemo/menuDemoOne/menuDemoOneTwo',
//     isShow: '1',
//     isRouter: '1',
//     sort: 0,
//   },
//   {
//     id: '3-2',
//     pid: '3',
//     name: '菜单测试2',
//     path: '/menuDemo/menuDemoTwo',
//     cmpPath: 'pages/menuDemo/menuDemoTwo',
//     isShow: '1',
//     isRouter: '1',
//     sort: 0,
//   },
// ];
